default_agent: websearch_agent
agents:
  main_agent:
    name: main_agent
    entrypoint: /Users/vasan/2 Areas/Repo/innovathon/agent_webserach/web_search.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: null
    aws:
      execution_role: arn:aws:iam::095059577505:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-dbcb276f38
      execution_role_auto_create: false
      account: 095059577505
      region: us-east-1
      ecr_repository: 095059577505.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-main_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: main_agent-LkFHfSDRP1
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:095059577505:runtime/main_agent-LkFHfSDRP1
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-main_agent-builder
      execution_role: arn:aws:iam::095059577505:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-dbcb276f38
      source_bucket: bedrock-agentcore-codebuild-sources-095059577505-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  websearch_agent:
    name: websearch_agent
    entrypoint: /Users/vasan/2 Areas/Repo/innovathon/agent_webserach/web_search.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: null
    aws:
      execution_role: arn:aws:iam::095059577505:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-232324e6ec
      execution_role_auto_create: false
      account: 095059577505
      region: us-east-1
      ecr_repository: 095059577505.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-websearch_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: websearch_agent-Slv3QACoYg
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:095059577505:runtime/websearch_agent-Slv3QACoYg
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-websearch_agent-builder
      execution_role: arn:aws:iam::095059577505:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-232324e6ec
      source_bucket: bedrock-agentcore-codebuild-sources-095059577505-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
