default_agent: arch_diag_agent
agents:
  arch_diag_agent:
    name: arch_diag_agent
    entrypoint: /Users/vasan/2 Areas/Repo/innovathon/agent_arch_diag_agent/arch_diag_agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: null
    aws:
      execution_role: arn:aws:iam::095059577505:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-5ec3949b5b
      execution_role_auto_create: false
      account: 095059577505
      region: us-east-1
      ecr_repository: 095059577505.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-arch_diag_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: arch_diag_agent-LQ6klZHOPF
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:095059577505:runtime/arch_diag_agent-LQ6klZHOPF
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-arch_diag_agent-builder
      execution_role: arn:aws:iam::095059577505:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-5ec3949b5b
      source_bucket: bedrock-agentcore-codebuild-sources-095059577505-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
