default_agent: migration_agent
agents:
  migration_agent:
    name: migration_agent
    entrypoint: /Users/vasan/2 Areas/Repo/innovathon/migration_agent/migration_agent.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::095059577505:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-1f9cc3803e
      execution_role_auto_create: false
      account: 095059577505
      region: us-east-1
      ecr_repository: 095059577505.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-migration_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: migration_agent-yss0vU3nxI
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:095059577505:runtime/migration_agent-yss0vU3nxI
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-migration_agent-builder
      execution_role: arn:aws:iam::095059577505:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-1f9cc3803e
      source_bucket: bedrock-agentcore-codebuild-sources-095059577505-us-east-1
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
  orchestrator_agent:
    name: orchestrator_agent
    entrypoint: /Users/vasan/2 Areas/Repo/innovathon/migration_agent/orchestrator.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::095059577505:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-00cafffea8
      execution_role_auto_create: false
      account: 095059577505
      region: us-east-1
      ecr_repository: 095059577505.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-orchestrator_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: orchestrator_agent-wGURHA9Rcw
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:095059577505:runtime/orchestrator_agent-wGURHA9Rcw
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-orchestrator_agent-builder
      execution_role: arn:aws:iam::095059577505:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-00cafffea8
      source_bucket: bedrock-agentcore-codebuild-sources-095059577505-us-east-1
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
  diagram_agent:
    name: diagram_agent
    entrypoint: /Users/vasan/2 Areas/Repo/innovathon/migration_agent/diag_test.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::095059577505:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-ed781db1d2
      execution_role_auto_create: false
      account: 095059577505
      region: us-east-1
      ecr_repository: 095059577505.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-diagram_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: diagram_agent-SjZNtSCaIC
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:095059577505:runtime/diagram_agent-SjZNtSCaIC
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-diagram_agent-builder
      execution_role: arn:aws:iam::095059577505:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-ed781db1d2
      source_bucket: bedrock-agentcore-codebuild-sources-095059577505-us-east-1
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
