default_agent: migration_agent_test
agents:
  migration_agent:
    name: migration_agent
    entrypoint: /Users/vasan/2 Areas/Repo/innovathon/migration_agent/migration_agent.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::095059577505:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-1f9cc3803e
      execution_role_auto_create: false
      account: 095059577505
      region: us-east-1
      ecr_repository: 095059577505.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-migration_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: migration_agent-yss0vU3nxI
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:095059577505:runtime/migration_agent-yss0vU3nxI
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-migration_agent-builder
      execution_role: arn:aws:iam::095059577505:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-1f9cc3803e
      source_bucket: bedrock-agentcore-codebuild-sources-095059577505-us-east-1
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
  migration_agent_test:
    name: migration_agent_test
    entrypoint: C:/Users/Aravind/Documents/project/AWS/innovathon/migration_agent/migration_agent.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::095059577505:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-922e2db63c
      execution_role_auto_create: false
      account: 095059577505
      region: us-east-1
      ecr_repository: 095059577505.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-migration_agent_test
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: migration_agent_test-FwBeBU9Rmr
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:095059577505:runtime/migration_agent_test-FwBeBU9Rmr
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-migration_agent_test-builder
      execution_role: arn:aws:iam::095059577505:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-922e2db63c
      source_bucket: bedrock-agentcore-codebuild-sources-095059577505-us-east-1
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
